name: Bug Report
description: File a bug report
title: "🪲 [Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: Description
    attributes:
      label: Please enter an explicit description of your issue
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I was trying to _, when I encountered _."
    validations:
      required: true
  - type: textarea
    id: Expectation & Results
    attributes:
      lablel: Please enter what you were expecting to happen and what occured
      description: This allows trivial developers to easily confirm bug
      placeholder: Tell us what you see!
      value: "I expected _ to occur when _, but I was instead presented with _."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Include steps to reproduce
      description: What steps did you take for the error to occur?
      placeholder: Step 1 
      value: 1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
